// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package main

import "encoding/json"
import "fmt"

type RunnableSchemaJson struct {
	// In corresponds to the JSON schema field "in".
	In interface{} `json:"in,omitempty" yaml:"in,omitempty" mapstructure:"in,omitempty"`

	// InSha256 corresponds to the JSON schema field "in.sha256".
	InSha256 interface{} `json:"in.sha256,omitempty" yaml:"in.sha256,omitempty" mapstructure:"in.sha256,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Notify corresponds to the JSON schema field "notify".
	Notify map[string]interface{} `json:"notify,omitempty" yaml:"notify,omitempty" mapstructure:"notify,omitempty"`

	// Out corresponds to the JSON schema field "out".
	Out *string `json:"out,omitempty" yaml:"out,omitempty" mapstructure:"out,omitempty"`

	// OutSha256 corresponds to the JSON schema field "out.sha256".
	OutSha256 *string `json:"out.sha256,omitempty" yaml:"out.sha256,omitempty" mapstructure:"out.sha256,omitempty"`

	// Post corresponds to the JSON schema field "post".
	Post *string `json:"post,omitempty" yaml:"post,omitempty" mapstructure:"post,omitempty"`

	// Pre corresponds to the JSON schema field "pre".
	Pre *string `json:"pre,omitempty" yaml:"pre,omitempty" mapstructure:"pre,omitempty"`

	// Run corresponds to the JSON schema field "run".
	Run *string `json:"run,omitempty" yaml:"run,omitempty" mapstructure:"run,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RunnableSchemaJson) UnmarshalJSON(value []byte) error {
	type Plain RunnableSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.OutSha256 != nil && len(*plain.OutSha256) < 64 {
		return fmt.Errorf("field %s length: must be >= %d", "out.sha256", 64)
	}
	if plain.OutSha256 != nil && len(*plain.OutSha256) > 64 {
		return fmt.Errorf("field %s length: must be <= %d", "out.sha256", 64)
	}
	*j = RunnableSchemaJson(plain)
	return nil
}
